### ISSUE TITLE
Register as package

### ISSUE THREAD

**Issue by tamasgal** [JuliaHEP/LandauDistribution.jl#3]
Any plans to register it? I'm already using it on a daily basis`:D`

**Comment by Moelf** [comment]
cloud use some tests

**Comment by tamasgal** [comment]
Yes indeed! I'll add some this week.

**Comment by tamasgal** [comment]
With a bit of delay, I added a few tests together with the PDF/CDF fix here: https://github.com/JuliaHEP/LandauDistribution.jl/pull/4

**Comment by Moelf** [comment]
https://github.com/JuliaRegistries/General/pull/44975#issuecomment-920821618
